# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca70947057fef58bafb290d711b1399cd6358492b5ee3f697a72ddd114a858c1d29b4e3ac94343d2ec20ff565550094f65993a5203f541e1467c1b807db320f9

test:
  secret_key_base: bf2c0bdd7c386684586372f6c77927b9aea841cfc2b3230256e3cd75c8b7dc04e6cf5d4d9fac9af5f20bf67b813fa76186d386b9aab130a5729166f0c8900a8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
